---
fluor_3031:
  EPIC_KEY: 3031
  fortran: f10.2
  generic_name: fluor
  longname: 'fluorometer'
  name: fluor
  units: volts
Fch_906: 
  EPIC_KEY: 906
  name: Fch
  generic_name: ''
  fortran: f10.1
  EPIC_KEY: 906
  units: ugrams/l
  longname: 'Chlorophyll A'
fluorstd_2031: 
  EPIC_KEY: 2031
  name: fluorstd
  generic_name: std
  fortran: 'f10.1'
  units: 'ugrams/l'
  longname: 'Standard Deviation fluor counts'
Trb_980:
  EPIC_KEY: 980
  fortran: f10.2
  generic_name: trb
  longname: 'Turbidity(FNU)'
  name: turb
  units: 'Formazin Nephelometric Units'
  #note - need to add CDOM to this for the ecobbfl2w
