---
fluor_3031:
  EPIC_KEY: 3031
  fortran: f10.2
  generic_name: fluor
  longname: 'fluorometer'
  name: fluor
  units: volts
Fch_906: 
  EPIC_KEY: 906
  name: Fch
  generic_name: ''
  fortran: f10.1
  EPIC_KEY: 906
  units: ugrams/l
  longname: 'Chlorophyll A'
fluorstd_2031: 
  EPIC_KEY: 2031
  name: fluorstd
  generic_name: std
  fortran: 'f10.1'
  units: 'ugrams/l'
  longname: 'Standard Deviation fluor counts'
Trb_2980:
  EPIC_KEY: 2980
  fortran: f10.2
  generic_name: trb
  longname: 'Turbidity (NTU)'
  name: turb
  units: 'Nephlometric Turbidity Units'
  #note - this should actully be NTU but that doesn't exist in EPIC
  #counts and std should be here too
