  - package-ecosystem: "pip"
    # Look for `build.gradle` in the `root` directory
    directory: "/"
    # Check for updates once weekly (daily to start)
    schedule:
      interval: "daily"
      ignore:
      # Ignore updates to packages that start 'aws'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: "flask*"
